
import random
import uuid
import datetime
import json

def rnd_item(l): return random.choice(l)
def rnd_pk(): return "aleo1" + "".join(random.choices("0123456789abcdef", k=58))
def rnd_hash(): return "0x" + "".join(random.choices("0123456789abcdef", k=64))

COUNTRIES = [
    "Nigeria", "Kenya", "South Africa", "Ghana", "Ethiopia", "Rwanda", "Uganda", "Tanzania"
]

REGIONS = {
    "Nigeria": ["Lagos", "Abuja", "Port Harcourt", "Kano"],
    "Kenya": ["Nairobi", "Mombasa", "Kisumu"],
    "South Africa": ["Cape Town", "Johannesburg", "Durban"],
    "Ghana": ["Accra", "Kumasi"],
    "Ethiopia": ["Addis Ababa"],
    "Rwanda": ["Kigali"],
    "Uganda": ["Kampala"],
    "Tanzania": ["Dar es Salaam"]
}

SQL_FILE = "mock_data.sql"
NUM_NODES = 300

print(f"Generating {NUM_NODES} nodes...")

with open(SQL_FILE, "w") as f:
    f.write("-- Mock Data for Nodes of You (300 Entries)\n")
    f.write("-- Generated by Antigravity\n\n")

    node_ids = []

    # 1. NODES
    f.write("-- 1. NODES\n")
    for _ in range(NUM_NODES):
        uid = str(uuid.uuid4())
        node_ids.append(uid)
        pub_key = rnd_pk()
        zk_hash = json.dumps({"proof": rnd_hash(), "method": "Groth16"})
        tier = random.choices([1, 2, 3, 4], weights=[40, 30, 20, 10])[0]
        
        f.write(f"INSERT INTO nodes (id, public_key, zk_proof_hash, tier_level) VALUES ('{uid}', '{pub_key}', '{zk_hash}', {tier});\n")

    f.write("\n\n-- 2. ENCRYPTED_PROFILES\n")
    # 2. PROFILES
    for uid in node_ids:
        country = rnd_item(COUNTRIES)
        region = rnd_item(REGIONS[country])
        age_bracket = rnd_item(["18-25", "26-35", "36-50", "51+"])
        crypto_exp = random.randint(2015, 2024)
        is_candidate = random.random() < 0.15 
        
        # NEW: Richer Financials & Participation
        # Holdings: Power law distribution (most have little, few have a lot)
        holdings = int(random.expovariate(1/5000)) + 50 # Base $50
        
        # Staking: 30% of users stake. Stakers usually have more holdings.
        is_staker = random.random() < 0.3
        staking_bal = int(holdings * random.uniform(0.2, 0.8)) if is_staker else 0
        
        # Node Ops: Rare (5%), generally high holdings
        is_validator = random.random() < 0.05
        if is_validator: 
            holdings += random.randint(10000, 50000)
            staking_bal += random.randint(5000, 20000)

        wa_hash = "enc_" + "".join(random.choices("0123456789abcdef", k=32))
        
        f.write(f"INSERT INTO encrypted_profiles (id, whatsapp_hash, country, region, age_bracket, crypto_experience_year, is_interview_candidate, estimated_holdings_usd, staking_balance_usd, is_validator) VALUES ('{uid}', '{wa_hash}', '{country}', '{region}', '{age_bracket}', {crypto_exp}, {'TRUE' if is_candidate else 'FALSE'}, {holdings}, {staking_bal}, {'TRUE' if is_validator else 'FALSE'});\n")

    f.write("\n\n-- 3. REVENUE_LEDGER\n")
    # 3. LEDGER
    for uid in node_ids:
        # 50% chance of having earnings
        if random.random() < 0.5:
            num_tx = random.randint(1, 5)
            for _ in range(num_tx):
                amount = round(random.uniform(5.0, 500.0), 2)
                src = rnd_item(['YouTube_RevShare', 'Referral', 'Grant', 'Staking_Reward'])
                status = rnd_item(['Paid', 'Pending', 'Staked'])
                
                f.write(f"INSERT INTO revenue_ledger (node_id, amount_usd, source, status) VALUES ('{uid}', {amount}, '{src}', '{status}');\n")

print(f"Done! Written to {SQL_FILE}")
